export interface KnowledgeEntry {
  id: string;
  title: string;
  url: string;
  text: string;
  keywords: string[];
}

// Public, deliberately curated facts only. Never add private contact details,
// unpublished work, customer data, or claims that are not already public.
export const knowledge: KnowledgeEntry[] = [
  {
    id: 'profile',
    title: 'Professional profile',
    url: '/about',
    text: 'Sarah D is a senior data scientist whose work spans production machine learning, applied AI, enterprise learning, knowledge systems, AI security, cybersecurity data, and threat intelligence. She focuses on systems that must operate reliably under real infrastructure, data-quality, product, and security constraints.',
    keywords: [
      'profile',
      'background',
      'summary',
      'specialty',
      'focus',
      'data scientist',
    ],
  },
  {
    id: 'roles',
    title: 'Target roles',
    url: '/recruiter',
    text: 'Relevant roles include Senior Data Scientist, Senior Machine Learning Engineer, Applied Scientist, AI Security Engineer, AI Security Researcher, Applied AI Engineer, and Principal AI Technologist.',
    keywords: ['roles', 'job', 'position', 'hiring', 'opportunity', 'career'],
  },
  {
    id: 'experience-timeline',
    title: 'AI, machine-learning, and cybersecurity experience timeline',
    url: '/resume',
    text: 'As of July 2026, Sarah has more than 10 years of cybersecurity and data experience, including machine-learning work dating to 2016. That timeline includes phishing detection and security analytics with Cisco Talos from March 2016 to October 2023; two years focused specifically on production generative AI, retrieval-augmented generation, semantic search, and LLM applications with Cisco Learning and Development from November 2023 to November 2025; and production machine-learning and AI-assisted cybersecurity work at ThreatSTOP since December 2024. Overlapping roles are not double-counted.',
    keywords: [
      'years',
      'experience',
      'how long',
      'ai experience',
      'machine learning experience',
      'generative ai experience',
      'timeline',
      'ten years',
    ],
  },
  {
    id: 'threatstop',
    title: 'Current security-focused data science work',
    url: '/resume',
    text: 'Since December 2024, Sarah has worked as a Senior Data Scientist at ThreatSTOP. Her public résumé describes leading development and deployment of machine-learning pipelines for phishing detection in DNS traffic on AWS; a multi-stage ensemble using Random Forest, Gradient Boosting, Logistic Regression, and Linear SVC; post-model analysis using DNS, WHOIS, DGA, and threat-intelligence signals; scalable data pipelines; and an Atlassian MCP connector for AI-powered Confluence knowledge retrieval.',
    keywords: [
      'threatstop',
      'current',
      'phishing',
      'dns',
      'whois',
      'aws',
      'security',
      'ai',
      'machine learning',
    ],
  },
  {
    id: 'cisco-ai',
    title: 'Applied AI and learning systems experience',
    url: '/resume',
    text: 'From November 2023 to November 2025, Sarah worked as a Data Scientist and AI Engineer with Cisco Learning and Development. She led the Cisco U. Generative AI services team and designed, deployed, and maintained a production retrieval-augmented generation chatbot on AWS. Her work also included semantic search, enterprise knowledge retrieval, LLM-powered user experiences, telemetry and feedback analysis, a graph-based data-catalog initiative for recommendation systems, automated reporting, and AI-service quality metrics.',
    keywords: [
      'cisco',
      'rag',
      'chatbot',
      'generative ai',
      'semantic search',
      'learning',
      'years',
      'experience',
      'lead',
      'led',
      'leadership',
      'team',
    ],
  },
  {
    id: 'cisco-talos',
    title: 'Cybersecurity experience',
    url: '/resume',
    text: 'From March 2016 to October 2023, Sarah worked as a Security Engineer with Cisco Talos. Her public résumé describes phishing URL detection, machine-learning models, threat-intelligence reporting automation, statistical analysis of security data, and cyber threat-intelligence databases.',
    keywords: [
      'talos',
      'cisco',
      'security engineer',
      'cybersecurity',
      'threat intelligence',
      'phishing',
      'ai',
      'machine learning',
      'years',
    ],
  },
  {
    id: 'skills',
    title: 'Technical skills',
    url: '/recruiter',
    text: 'Publicly listed technical areas include Python, SQL, Bash, scikit-learn, AWS, S3, Redis, Pinecone, DocumentDB, PostgreSQL, MySQL, OpenSearch, Elastic Stack, CircleCI, retrieval-augmented generation, AI agents, chatbot development, semantic search, DNS, WHOIS, Docker, Kubernetes, Git, REST APIs, statistics, data cleaning, regular expressions, Tableau, Excel, and data visualization.',
    keywords: [
      'skills',
      'tools',
      'stack',
      'python',
      'sql',
      'aws',
      'docker',
      'kubernetes',
      'cloud',
      'data technologies',
      'data platforms',
      'database',
      'redis',
      'pinecone',
      'postgresql',
    ],
  },
  {
    id: 'education',
    title: 'Education',
    url: '/resume',
    text: 'Sarah holds an MS in Environmental Science and Policy from George Mason University and a BA in English and Business Economics from the University of Kassel in Germany.',
    keywords: [
      'education',
      'degree',
      'university',
      'school',
      'masters',
      'bachelor',
    ],
  },
  {
    id: 'approach',
    title: 'Engineering approach',
    url: '/about',
    text: 'Sarah treats production readiness as more than deploying a model. Her approach includes security and privacy boundaries, scalable architecture, data quality, evaluation, logging, observability, monitoring, cost and latency controls, failure handling, human review, versioning, rollback plans, and feedback loops. Her portfolio presents AI as an end-to-end system involving data, retrieval, models, infrastructure, operations, and human judgment.',
    keywords: [
      'approach',
      'philosophy',
      'production',
      'reliability',
      'evaluation',
      'monitoring',
      'logging',
      'observability',
      'scalability',
      'production ready',
      'production readiness',
      'latency',
      'cost',
      'rollback',
    ],
  },
  {
    id: 'portfolio-rag-agent',
    title: 'RAG-based LLM portfolio agent',
    url: '/#portfolio-assistant',
    text: 'Sarah built the RAG-based LLM agent available throughout this portfolio. It retrieves relevant facts from a deliberately curated public knowledge base covering her résumé, experience, skills, writing, engineering approach, and projects. A small LLM hosted through Cloudflare Workers AI writes a short answer using only the retrieved facts and returns citations to the supporting pages. Deterministic answers handle sensitive or easily misstated questions. The application also uses origin checks, Turnstile verification, bounded inputs, prompt-injection detection, private-data blocking, output sanitization, optional per-session and global rate-limit bindings, and privacy-aware history retention.',
    keywords: [
      'portfolio agent',
      'portfolio chatbot',
      'rag chatbot',
      'rag agent',
      'llm agent',
      'this chatbot',
      'this agent',
      'retrieval augmented generation',
      'cloudflare workers ai',
      'citations',
      'tamper resistant',
      'prompt injection',
    ],
  },
  {
    id: 'domain-research-agent',
    title: 'AI Security Research Agent project',
    url: '/projects/ai-security-research-agent-poc',
    text: 'Sarah built a working, read-only AI domain-research agent. It validates one public domain, collects passive DNS, RDAP registration, and Certificate Transparency evidence, and can optionally retrieve an existing VirusTotal report with a visitor-supplied key. Cloudflare Workers AI compares the bounded evidence and returns a structured verdict. Deterministic guardrails preserve failed sources, cap confidence when reputation data is missing, prevent the model from calling a domain safe, and force an inconclusive result when evidence is too limited. The agent cannot browse arbitrary URLs, scan domains, run commands, or store the optional VirusTotal key.',
    keywords: [
      'ai security research agent',
      'security research agent',
      'domain research agent',
      'domain agent',
      'researcher agent',
      'research project',
      'project',
      'projects',
      'dns',
      'rdap',
      'certificate transparency',
      'virustotal',
      'verdict',
      'read only',
    ],
  },
  {
    id: 'ml-phishing-domain-detection',
    title: 'ML Phishing Domain Detection',
    url: '/projects/ml-phishing-domain-detection',
    text: 'At ThreatSTOP, Sarah built a production machine-learning system that screens live DNS traffic and flags malicious or look-alike phishing domains in near real time. A four-model ensemble—Random Forest, Gradient Boosting, Logistic Regression, and LinearSVC—uses more than 50 engineered domain features and independently tuned decision thresholds. A separate three-stage safety net checks domain age and structure, VirusTotal consensus, and WHOIS, infrastructure, and lexical signals before action. Recent production results described on the portfolio are roughly 800 malicious or suspicious domains flagged and blocked per day and about 90% precision on live traffic. The containerized Kubernetes worker versions model artifacts in S3 with ETag caching, exposes Prometheus metrics, reports errors to Sentry, and feeds reviewed verdicts back into retraining.',
    keywords: [
      'ml phishing domain detection',
      'phishing detection',
      'malicious domains',
      'look alike domains',
      'dns traffic',
      'ensemble',
      'random forest',
      'gradient boosting',
      'logistic regression',
      'linearsvc',
      'safety net',
      'virustotal',
      'kubernetes',
      'prometheus',
      'sentry',
      'threatstop',
      'project',
      'projects',
    ],
  },
  {
    id: 'threatstop-writing',
    title: 'Published ThreatSTOP articles',
    url: '/writing',
    text: 'Sarah has published two professional articles at ThreatSTOP: “Enhancing DNS Security with Machine Learning” in June 2025, explaining how similarity, structural, character-pattern, and threat-intelligence signals strengthen protective DNS; and “The Simplest Science Behind Domain Similarity” in September 2025, introducing Levenshtein distance, homograph normalization, and look-alike-domain detection.',
    keywords: [
      'writing',
      'articles',
      'publications',
      'published',
      'threatstop blog',
      'domain similarity',
      'dns security',
      'levenshtein',
    ],
  },
  {
    id: 'boundaries',
    title: 'Public information boundaries',
    url: '/contact',
    text: 'The portfolio intentionally does not publish private contact details, confidential employer information, customer information, proprietary code, compensation, personal references, or non-public project details. Visitors should use the public contact route for an appropriate follow-up.',
    keywords: [
      'contact',
      'email',
      'phone',
      'private',
      'confidential',
      'salary',
      'reference',
    ],
  },
];
