export interface KnowledgeEntry {
  id: string;
  title: string;
  url: string;
  text: string;
  keywords: string[];
}

// Public, deliberately curated facts only. Never add private contact details,
// unpublished work, customer data, or claims that are not already public.
export const knowledge: KnowledgeEntry[] = [
  {
    id: 'profile',
    title: 'Professional profile',
    url: '/about',
    text: 'Sarah D is a senior data scientist whose work combines production machine learning, applied AI, AI security, cybersecurity data, and threat intelligence. She focuses on systems that must operate reliably under real infrastructure, data-quality, and security constraints.',
    keywords: [
      'profile',
      'background',
      'summary',
      'specialty',
      'focus',
      'data scientist',
    ],
  },
  {
    id: 'roles',
    title: 'Target roles',
    url: '/recruiter',
    text: 'Relevant roles include Senior Data Scientist, Senior Machine Learning Engineer, Applied Scientist, AI Security Engineer, AI Security Researcher, Applied AI Engineer, and Principal AI Technologist.',
    keywords: ['roles', 'job', 'position', 'hiring', 'opportunity', 'career'],
  },
  {
    id: 'experience-timeline',
    title: 'AI, machine-learning, and cybersecurity experience timeline',
    url: '/resume',
    text: 'As of July 2026, Sarah has more than 10 years of professional AI and machine-learning experience, dating from March 2016. That timeline includes machine-learning phishing detection and security analytics with Cisco Talos from March 2016 to October 2023; production generative AI, retrieval-augmented generation, semantic search, and LLM applications with Cisco Learning and Development from November 2023 to November 2025; and production machine-learning and AI-assisted cybersecurity work at ThreatSTOP since December 2024. Overlapping roles are not double-counted. Her specifically generative-AI-focused role represents two years from November 2023 to November 2025.',
    keywords: [
      'years',
      'experience',
      'how long',
      'ai experience',
      'machine learning experience',
      'generative ai experience',
      'timeline',
      'ten years',
    ],
  },
  {
    id: 'threatstop',
    title: 'Current security-focused data science work',
    url: '/resume',
    text: 'Since December 2024, Sarah has worked as a Senior Data Scientist at ThreatSTOP. Her public résumé describes leading development and deployment of machine-learning pipelines for phishing detection in DNS traffic on AWS; a multi-stage ensemble using Random Forest, Gradient Boosting, Logistic Regression, and Linear SVC; post-model analysis using DNS, WHOIS, DGA, and threat-intelligence signals; scalable data pipelines; and an Atlassian MCP connector for AI-powered Confluence knowledge retrieval.',
    keywords: [
      'threatstop',
      'current',
      'phishing',
      'dns',
      'whois',
      'aws',
      'security',
      'ai',
      'machine learning',
    ],
  },
  {
    id: 'cisco-ai',
    title: 'Applied AI and learning systems experience',
    url: '/resume',
    text: 'From November 2023 to November 2025, Sarah worked as a Data Scientist and AI Engineer with Cisco Learning and Development. She led the Cisco U. Generative AI services team and designed, deployed, and maintained a production retrieval-augmented generation chatbot on AWS. Her work also included semantic search, enterprise knowledge retrieval, LLM-powered user experiences, telemetry and feedback analysis, a graph-based data-catalog initiative for recommendation systems, automated reporting, and AI-service quality metrics.',
    keywords: [
      'cisco',
      'rag',
      'chatbot',
      'generative ai',
      'semantic search',
      'learning',
      'years',
      'experience',
      'lead',
      'led',
      'leadership',
      'team',
    ],
  },
  {
    id: 'cisco-talos',
    title: 'Cybersecurity experience',
    url: '/resume',
    text: 'From March 2016 to October 2023, Sarah worked as a Security Engineer with Cisco Talos. Her public résumé describes phishing URL detection, machine-learning models, threat-intelligence reporting automation, statistical analysis of security data, and cyber threat-intelligence databases.',
    keywords: [
      'talos',
      'cisco',
      'security engineer',
      'cybersecurity',
      'threat intelligence',
      'phishing',
      'ai',
      'machine learning',
      'years',
    ],
  },
  {
    id: 'skills',
    title: 'Technical skills',
    url: '/recruiter',
    text: 'Publicly listed technical areas include Python, SQL, Bash, scikit-learn, AWS, S3, Redis, Pinecone, DocumentDB, PostgreSQL, MySQL, OpenSearch, Elastic Stack, CircleCI, retrieval-augmented generation, AI agents, chatbot development, semantic search, DNS, WHOIS, Docker, Kubernetes, Git, REST APIs, statistics, data cleaning, regular expressions, Tableau, Excel, and data visualization.',
    keywords: [
      'skills',
      'tools',
      'stack',
      'python',
      'sql',
      'aws',
      'docker',
      'kubernetes',
      'cloud',
      'data technologies',
      'data platforms',
      'database',
      'redis',
      'pinecone',
      'postgresql',
    ],
  },
  {
    id: 'education',
    title: 'Education',
    url: '/resume',
    text: 'Sarah holds an MS in Environmental Science and Policy from George Mason University and a BA in English and Business Economics from the University of Kassel in Germany.',
    keywords: [
      'education',
      'degree',
      'university',
      'school',
      'masters',
      'bachelor',
    ],
  },
  {
    id: 'approach',
    title: 'Engineering approach',
    url: '/about',
    text: 'Sarah emphasizes production reliability, evaluation, failure modes, data quality, security context, monitoring, and operational constraints. Her portfolio presents AI as an end-to-end system involving data, retrieval, models, infrastructure, feedback, and human judgment.',
    keywords: [
      'approach',
      'philosophy',
      'production',
      'reliability',
      'evaluation',
      'monitoring',
    ],
  },
  {
    id: 'threatstop-writing',
    title: 'Published ThreatSTOP articles',
    url: '/writing',
    text: 'Sarah has published two professional articles at ThreatSTOP: “Enhancing DNS Security with Machine Learning” in June 2025, explaining how similarity, structural, character-pattern, and threat-intelligence signals strengthen protective DNS; and “The Simplest Science Behind Domain Similarity” in September 2025, introducing Levenshtein distance, homograph normalization, and look-alike-domain detection.',
    keywords: [
      'writing',
      'articles',
      'publications',
      'published',
      'threatstop blog',
      'domain similarity',
      'dns security',
      'levenshtein',
    ],
  },
  {
    id: 'boundaries',
    title: 'Public information boundaries',
    url: '/contact',
    text: 'The portfolio intentionally does not publish private contact details, confidential employer information, customer information, proprietary code, compensation, personal references, or non-public project details. Visitors should use the public contact route for an appropriate follow-up.',
    keywords: [
      'contact',
      'email',
      'phone',
      'private',
      'confidential',
      'salary',
      'reference',
    ],
  },
];
